sudo: required
services:
   - docker

before_install:
  - docker build -t jayanthanc/react-test -f ./client/Dockerfile.dev ./client
 
script:
  - docker run jayanthanc/react-test npm test -- --coverage

after_success:
  - docker build -t jayanathanc/multi-client ./client
  - docker build -t jayanathanc/multi-nginx ./nginx
  - docker build -t jayanathanc/multi-server ./server
  - docker build -t jayanathanc/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push jayanthanc/multi-client
  - docker push jayanthanc/multi-nginx
  - docker push jayanthanc/multi-server
  - docker push jayanthanc/multi-worker
